src/java/controlador/LocalidadesController.java
package controlador;

import entidad.Localidades;
import controlador.util.JsfUtil;
import controlador.util.JsfUtil.PersistAction;

import java.io.Serializable;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.ejb.EJBException;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;

@Named("localidadesController")
@SessionScoped
public class LocalidadesController implements Serializable {

    @EJB
    private controlador.LocalidadesFacade ejbFacade;
    private List<Localidades> items = null;
    private Localidades selected;

    public LocalidadesController() {
    }

    public Localidades getSelected() {
        return selected;
    }

    public void setSelected(Localidades selected) {
        this.selected = selected;
    }

    protected void setEmbeddableKeys() {
    }

    protected void initializeEmbeddableKey() {
    }

    private LocalidadesFacade getFacade() {
        return ejbFacade;
    }

    public Localidades prepareCreate() {
        selected = new Localidades();
        initializeEmbeddableKey();
        return selected;
    }

    public void create() {
        persist(PersistAction.CREATE, ResourceBundle.getBundle("/Bundle").getString("LocalidadesCreated"));
        if (!JsfUtil.isValidationFailed()) {
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public void update() {
        persist(PersistAction.UPDATE, ResourceBundle.getBundle("/Bundle").getString("LocalidadesUpdated"));
    }

    public void destroy() {
        persist(PersistAction.DELETE, ResourceBundle.getBundle("/Bundle").getString("LocalidadesDeleted"));
        if (!JsfUtil.isValidationFailed()) {
            selected = null; // Remove selection
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public List<Localidades> getItems() {
        if (items == null) {
            items = getFacade().findAll();
        }
        return items;
    }

    private void persist(PersistAction persistAction, String successMessage) {
        if (selected != null) {
            setEmbeddableKeys();
            try {
                if (persistAction != PersistAction.DELETE) {
                    getFacade().edit(selected);
                } else {
                    getFacade().remove(selected);
                }
                JsfUtil.addSuccessMessage(successMessage);
            } catch (EJBException ex) {
                String msg = "";
                Throwable cause = ex.getCause();
                if (cause != null) {
                    msg = cause.getLocalizedMessage();
                }
                if (msg.length() > 0) {
                    JsfUtil.addErrorMessage(msg);
                } else {
                    JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
                }
            } catch (Exception ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            }
        }
    }

    public Localidades getLocalidades(java.lang.Integer id) {
        return getFacade().find(id);
    }

    public List<Localidades> getItemsAvailableSelectMany() {
        return getFacade().findAll();
    }

    public List<Localidades> getItemsAvailableSelectOne() {
        return getFacade().findAll();
    }

    @FacesConverter(forClass = Localidades.class)
    public static class LocalidadesControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            LocalidadesController controller = (LocalidadesController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "localidadesController");
            return controller.getLocalidades(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Localidades) {
                Localidades o = (Localidades) object;
                return getStringKey(o.getIdSalon());
            } else {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "object {0} is of type {1}; expected type: {2}", new Object[]{object, object.getClass().getName(), Localidades.class.getName()});
                return null;
            }
        }

    }

}

web/localidades/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="LocalidadesCreateDlg" widgetVar="LocalidadesCreateDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.CreateLocalidadesTitle}">
            <h:form id="LocalidadesCreateForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{localidadesController.selected != null}">
                        <p:outputLabel value="#{bundle.CreateLocalidadesLabel_idSalon}" for="idSalon" />
                        <p:inputText id="idSalon" value="#{localidadesController.selected.idSalon}" title="#{bundle.CreateLocalidadesTitle_idSalon}" required="true" requiredMessage="#{bundle.CreateLocalidadesRequiredMessage_idSalon}"/>
                        <p:outputLabel value="#{bundle.CreateLocalidadesLabel_nombre}" for="nombre" />
                        <p:inputText id="nombre" value="#{localidadesController.selected.nombre}" title="#{bundle.CreateLocalidadesTitle_nombre}" required="true" requiredMessage="#{bundle.CreateLocalidadesRequiredMessage_nombre}"/>
                        <p:outputLabel value="#{bundle.CreateLocalidadesLabel_lugar}" for="lugar" />
                        <p:inputText id="lugar" value="#{localidadesController.selected.lugar}" title="#{bundle.CreateLocalidadesTitle_lugar}" required="true" requiredMessage="#{bundle.CreateLocalidadesRequiredMessage_lugar}"/>
                        <p:outputLabel value="#{bundle.CreateLocalidadesLabel_idCategoria}" for="idCategoria" />
                        <p:selectOneMenu id="idCategoria" value="#{localidadesController.selected.idCategoria}" required="true" requiredMessage="#{bundle.EditLocalidadesRequiredMessage_idCategoria}">
                            <f:selectItems value="#{categoriaController.itemsAvailableSelectOne}"
                                           var="idCategoriaItem"
                                           itemValue="#{idCategoriaItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{localidadesController.create}" value="#{bundle.Save}" update="display,:LocalidadesListForm:datalist,:growl" oncomplete="handleSubmit(args,'LocalidadesCreateDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="LocalidadesCreateDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

web/localidades/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="LocalidadesEditDlg" widgetVar="LocalidadesEditDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.EditLocalidadesTitle}">
            <h:form id="LocalidadesEditForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{localidadesController.selected != null}">
                        <p:outputLabel value="#{bundle.EditLocalidadesLabel_idSalon}" for="idSalon" />
                        <p:inputText id="idSalon" value="#{localidadesController.selected.idSalon}" title="#{bundle.EditLocalidadesTitle_idSalon}" required="true" requiredMessage="#{bundle.EditLocalidadesRequiredMessage_idSalon}"/>
                        <p:outputLabel value="#{bundle.EditLocalidadesLabel_nombre}" for="nombre" />
                        <p:inputText id="nombre" value="#{localidadesController.selected.nombre}" title="#{bundle.EditLocalidadesTitle_nombre}" required="true" requiredMessage="#{bundle.EditLocalidadesRequiredMessage_nombre}"/>
                        <p:outputLabel value="#{bundle.EditLocalidadesLabel_lugar}" for="lugar" />
                        <p:inputText id="lugar" value="#{localidadesController.selected.lugar}" title="#{bundle.EditLocalidadesTitle_lugar}" required="true" requiredMessage="#{bundle.EditLocalidadesRequiredMessage_lugar}"/>
                        <p:outputLabel value="#{bundle.EditLocalidadesLabel_idCategoria}" for="idCategoria" />
                        <p:selectOneMenu id="idCategoria" value="#{localidadesController.selected.idCategoria}" required="true" requiredMessage="#{bundle.EditLocalidadesRequiredMessage_idCategoria}">
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{categoriaController.itemsAvailableSelectOne}"
                                           var="idCategoriaItem"
                                           itemValue="#{idCategoriaItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{localidadesController.update}" value="#{bundle.Save}" update="display,:LocalidadesListForm:datalist,:growl" oncomplete="handleSubmit(args, 'LocalidadesEditDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="LocalidadesEditDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

web/localidades/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">


        <ui:define name="title">
            <h:outputText value="#{bundle.ListLocalidadesTitle}"></h:outputText>
        </ui:define>

        <ui:define name="body">
            <h:form id="LocalidadesListForm">
                <p:panel header="#{bundle.ListLocalidadesTitle}">
                    <p:dataTable id="datalist" value="#{localidadesController.items}" var="item"
                                 selectionMode="single" selection="#{localidadesController.selected}"
                                 paginator="true"
                                 rowKey="#{item.idSalon}"
                                 rows="10"
                                 rowsPerPageTemplate="10,20,30,40,50"
                                 >

                        <p:ajax event="rowSelect"   update="createButton viewButton editButton deleteButton"/>
                        <p:ajax event="rowUnselect" update="createButton viewButton editButton deleteButton"/>

                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListLocalidadesTitle_idSalon}"/>
                            </f:facet>
                            <h:outputText value="#{item.idSalon}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListLocalidadesTitle_nombre}"/>
                            </f:facet>
                            <h:outputText value="#{item.nombre}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListLocalidadesTitle_lugar}"/>
                            </f:facet>
                            <h:outputText value="#{item.lugar}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListLocalidadesTitle_idCategoria}"/>
                            </f:facet>
                            <h:outputText value="#{item.idCategoria}"/>
                        </p:column>
                        <f:facet name="footer">
                            <p:commandButton id="createButton" icon="ui-icon-plus"   value="#{bundle.Create}" actionListener="#{localidadesController.prepareCreate}" update=":LocalidadesCreateForm" oncomplete="PF('LocalidadesCreateDialog').show()"/>
                            <p:commandButton id="viewButton"   icon="ui-icon-search" value="#{bundle.View}" update=":LocalidadesViewForm" oncomplete="PF('LocalidadesViewDialog').show()" disabled="#{empty localidadesController.selected}"/>
                            <p:commandButton id="editButton"   icon="ui-icon-pencil" value="#{bundle.Edit}" update=":LocalidadesEditForm" oncomplete="PF('LocalidadesEditDialog').show()" disabled="#{empty localidadesController.selected}"/>
                            <p:commandButton id="deleteButton" icon="ui-icon-trash"  value="#{bundle.Delete}" actionListener="#{localidadesController.destroy}" update=":growl,datalist" disabled="#{empty localidadesController.selected}"/>
                        </f:facet>
                    </p:dataTable>
                </p:panel>
            </h:form>

            <ui:include src="Create.xhtml"/>
            <ui:include src="Edit.xhtml"/>
            <ui:include src="View.xhtml"/>
        </ui:define>
    </ui:composition>

</html>

web/localidades/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="LocalidadesViewDlg" widgetVar="LocalidadesViewDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.ViewLocalidadesTitle}">
            <h:form id="LocalidadesViewForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{localidadesController.selected != null}">
                        <h:outputText value="#{bundle.ViewLocalidadesLabel_idSalon}"/>
                        <h:outputText value="#{localidadesController.selected.idSalon}" title="#{bundle.ViewLocalidadesTitle_idSalon}"/>
                        <h:outputText value="#{bundle.ViewLocalidadesLabel_nombre}"/>
                        <h:outputText value="#{localidadesController.selected.nombre}" title="#{bundle.ViewLocalidadesTitle_nombre}"/>
                        <h:outputText value="#{bundle.ViewLocalidadesLabel_lugar}"/>
                        <h:outputText value="#{localidadesController.selected.lugar}" title="#{bundle.ViewLocalidadesTitle_lugar}"/>
                        <h:outputText value="#{bundle.ViewLocalidadesLabel_idCategoria}"/>
                        <h:outputText value="#{localidadesController.selected.idCategoria}" title="#{bundle.ViewLocalidadesTitle_idCategoria}"/>
                    </p:panelGrid>
                    <p:commandButton value="#{bundle.Close}" onclick="LocalidadesViewDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>